### PR TITLE
spiders: remove unused spiders

### PR DESCRIPTION
**Pull request by jacquerie**
## Motivation and Context:
The spiders removed in this PR were never used, or tested against a live system, or selected according to our priorities on what we should be harvesting. On the other hand they brought with them technical debt that is currently preventing us from delivering features faster.

## Checklist:
- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [x] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by david-caro** [comment]
did you add the major version bump?

**Comment by jacquerie** [comment]
> did you add the major version bump?

Err, no! Too late, or should I at least tag this commit?

**Comment by david-caro** [comment]
No need, did you talk with vojtiech? if he has no problem, we can move on.

**Comment by Dziolas** [comment]
Just talked with Jacopo. All is good :)

**Pull request merged**
