### PR TITLE
global: upgrade celery to 4.0.2 version

### PR DESCRIPTION
**Pull request by spirosdelviniotis**
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Why the PR? Just asking because if we merge it then we also need to merge https://github.com/inspirehep/inspire-next/pull/2138 but we are not yet fully ready there, AFAIK.

**Comment by david-caro** [comment]
@salmele yep, both depend on each other, but as the celery upgrade was way more complicated than expeced, it's currently on hold.

**Comment by kaplun** [comment]
Ahah! I guess you meant @kaplun :+1:

**Comment by david-caro** [comment]
Hahaha, yep, sa autocompletes to salvatore xd, sorry for the noise

**Comment by jacquerie** [comment]
Stale, will be resurrected if/when needed.

**Pull request closed without merging**
