### PR TITLE
global: fix travis build

### PR DESCRIPTION
**Pull request by spirosdelviniotis**
* Upgrade: `docker-compose` version to `1.13.0`.
* Removes: pinned Docker version (`1.12.3-0~trusty`)
* Re-factored: renamed `fix_venv_tmp_rights.c` to `fix_rights.c`.
* Re-factored: renamed `fix_venv_tmp_rights` to `fix_rights`.
* Re-factored: `docker_entrypoint.sh` to support `code` folder.
* Re-factored: `docker-compose.test.yml` fixed build issue. It was wrong linking of `scrapyd` service with `scrapy-deploy` service.
* Adds base user's `UID` and `GID`.
* Adds: permission to `code` and `tmp` directory for docker images.

Signed-off-by: Spiros Delviniotis <spirosdelviniotis@gmail.com>

### CODE REVIEW

**Comment by david-caro** [comment]
I looks like the coverage might be broken...

**Comment by spirosdelviniotis** [comment]
I am on it!

**Comment by jacquerie** [comment]
> I looks like the coverage might be broken...

NB: coverage has been broken on `inspire-next` for quite a while: https://github.com/inspirehep/inspire-next/issues/2387

**Comment by david-caro** [comment]
@jacquerie I think that the current coverage issue is due to https://github.com/inspirehep/inspire-next/pull/2468

About the acceptance one, seems another issue...

**Comment by spirosdelviniotis** [comment]
@david-caro it worked! :smile:

**Pull request merged**
