### PR TITLE
tests: fix failing tests after DoJSON update

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
## Related Issue

Due to https://github.com/inspirehep/inspire-dojson/commit/030fda8a00267a831d21264e4e8c3a57b2d04807 change DESY functional tests and some unit tests began failing. This fixes them.

## Checklist:

- [x] I have all the information that I need (if not, move to `RFC` and look for it).
- [ ] I linked the related issue(s) in the corresponding commit logs.
- [x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [x] My code follows the code style of this project.
- [ ] I've added any new docs if API/utils methods were added.
- [ ] I have updated the existing documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jacquerie** [comment]
Why do we have these tests in the first place? They look like [change detector](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html) tests to me; they don't help catch errors in DoJSON (which is extensively tested!), but they slow down development of HEPCrawl.

**Comment by david-caro** [comment]
@szymonlopaciuk I'm sorry for the delay, but I disagree with @jacquerie comments, can you restore the fixtures that were being used?

**Comment by jacquerie** [comment]
> but I disagree with @jacquerie comments

Can you detail your argument? I made two points:
1. These tests slow down development of HEPCrawl, because they make the status of its build depend on the output of INSPIRE-DoJSON, not just its API.
2. These tests are anyway not catching bugs, because INSPIRE-DoJSON is already extensively tested, and these big fixtures were generated by running the code and piping its output in the fixture file, effectively testing the implementation against itself.

**Comment by jacquerie** [comment]
We discussed this issue IRL: these tests act as a safeguard against changes in the schema, similar to how assertions like https://github.com/inspirehep/inspire-next/blob/e56c335d72570df80a6e87f1817b0a64cdd3c2c3/tests/unit/utils/test_utils_record.py#L48 in `inspire-next` help when bumping the schemas. While they are costly to maintain, they are the only way to achieve a similar result in HEPCrawl before more unit tests are written, so this is the way to go for now.

**Pull request merged**
